services:
  - type: web
    name: gemma-frontend-react
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: BACKEND_API_URL
        value: https://gemma-api.onrender.com
